services:
  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.126.0
    volumes:
      - ./log.txt:/tmp/log.txt
      - ./log.json:/tmp/log.json
      - ./error_log.txt:/tmp/error_log.txt
      - ./otelconf.yaml:/etc/otelcol-contrib/config.yaml
