name: Build

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up maven
        uses: s4u/setup-maven-action@4f7fb9d9675e899ca81c6161dadbba0189a4ebb1 # v1.18.0
        with:
          java-distribution: 'temurin'
          java-version: '11'
      - name: Check Weaver model
        run: make check
      - name: Check docs generation
        run: |
          make generate-docs
          git diff --exit-code || (echo 'Docs out of date')
      - name: Check config generation
        run: |
          make generate-yaml
          git diff --exit-code || (echo 'YAML out of date')
      - name: Check java generation
        run: |
          make generate-java
          ./gradlew spotlessApply
          git diff --exit-code || (echo 'Java out of date')
      - name: Maven build and test
        run: ./gradlew clean check shadowJar
