name: Run End to End tests

on:
  push:
    branches: [ main ]
  pull_request:


permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up maven
        uses: s4u/setup-maven-action@4f7fb9d9675e899ca81c6161dadbba0189a4ebb1 # v1.18.0
        with:
          java-distribution: 'temurin'
          java-version: '11'

      - name: Build the jar
        run: |
          ./mvnw package -DskipTests

      - name: Start MQ and the test services
        run: |
          cd golden
          docker compose up -d --wait

      - name: Run the integration
        run: |
          cd golden
          ./run.sh &
          exit_code=$(docker wait golden)
          docker logs golden
          if [ "$exit_code" -ne 0 ]; then
            exit 1
          fi
          
