name: Run End to End tests

on:
  push:
    branches: [ main ]
  pull_request:


permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Cache Docker images.
        uses: ScribeMD/docker-cache@fb28c93772363301b8d0a6072ce850224b73f74e # 0.5.0
        with:
          key: docker-mq-e2e
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up maven
        uses: s4u/setup-maven-action@4f7fb9d9675e899ca81c6161dadbba0189a4ebb1 # v1.18.0
        with:
          java-distribution: 'temurin'
          java-version: '11'

      - name: Build the jar
        run: |
          ./mvnw package -DskipTests

      - name: Start MQ and the test services
        run: |
          cd golden
          docker compose up -d --wait

      - name: Run the integration
        run: |
          cd golden
          ./run.sh &
          exit_code=$(docker wait golden)
          docker logs golden
          if [ "$exit_code" -ne 0 ]; then
            exit 1
          fi
      - name: Notify failed build
        uses: jayqi/failed-build-issue-action@1a893bbf43ef1c2a8705e2b115cd4f0fe3c5649b # v1.2.0
        if: failure() && github.event.pull_request == null
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
