name: Run MQ Integration Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mq:
        image: icr.io/ibm-messaging/mq:latest
        ports:
          - 1414:1414
          - 9443:9443
        env:
          LICENSE: accept
          MQ_QMGR: QM1
          MQ_APP_PASSWORD: passw0rd
        options: >-
          --name mqtest
          --memory=2g
          --cpus=1
          --health-cmd="echo 'SET' | /opt/mqm/bin/runmqsc QM1"
          --health-interval=10s
          --health-timeout=20s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Wait for MQ to become healthy
        run: |
          for i in {1..30}; do
            if docker inspect --format='{{.State.Health.Status}}' mqtest | grep -q "healthy"; then
              echo "MQ is healthy!"
              break
            fi
            echo "Waiting for MQ to be healthy..."
            sleep 10
          done

      - name: Run integration tests
        run: mvn verify
