name: Run MQ Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      ibm-mq:
        image: icr.io/ibm-messaging/mq:9.4.2.1-r1
        ports:
          - 1414:1414
          - 9443:9443
        env:
          LICENSE: accept
          MQ_QMGR_NAME: QM1
          MQ_ADMIN_USER: admin
          MQ_ADMIN_PASSWORD: passw0rd
          MQ_APP_USER: app
          MQ_APP_PASSWORD: passw0rd # deprecated, but needed for app user in some setups
          MQ_ENABLE_METRICS: true
        options: >-
          --name ibm-mq-test
          --health-cmd "echo > /dev/tcp/localhost/1414"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Cache Docker images.
        uses: AndreKurait/docker-cache@0fe76702a40db986d9663c24954fc14c6a6031b7 # 0.6.0
        with:
          key: docker-mq-integration
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up maven
        uses: s4u/setup-maven-action@4f7fb9d9675e899ca81c6161dadbba0189a4ebb1 # v1.18.0
        with:
          java-distribution: 'temurin'
          java-version: '11'

      - name: Wait for MQ to be ready
        run: |
          echo "Waiting for MQ to start..."
          for i in {1..30}; do
            docker exec ibm-mq-test dspmq | grep -q "Running" && break
            sleep 5
          done
          docker exec ibm-mq-test dspmq

      - name: Run Integration Tests
        run: |
          echo "Running integration tests"
          ./mvnw verify

